### ISSUE TITLE
Support for field and enum-value markers/deprecations in conjure definition

### ISSUE THREAD

**Issue by nathklei** [palantir/conjure#120]
It would be useful to add the ability to specify markers on individual fields and enum values to conjure definitions. 

The initial use case that this request is deprecating fields and enum values. In models or enums that are used widely, it may not be feasible to create full replacements (e.g. Person2 replaces Person). By marking a field deprecated, tooling could be used to ensure deprecated fields are removed following major releases, as an example.

Workarounds such as adding keywords in docs would work, but may clutter up useful documentation and wouldn't be portable.

**Comment by gm2211** [comment]
Is there any update on this? Looking at the PR, the change was rejected because we don't have a very well defined process for changes to the IR - any progress on that?
