### ISSUE TITLE
allow external types to be used as header parameters

### ISSUE THREAD

**Issue by rubenfiszel** [palantir/conjure#171]
## Motivation

Currently, there seems to be no way to define a custom header. 
`auth: header` is always an `AuthHeader`

## Proposal

Support TypeName in auth. One possible syntax:

```
auth: 
  customHeader: MyTypeName
```

**Comment by markelliot** [comment]
one can declare custom headers of any primitive-like type as parameters on any endpoint

**Comment by rubenfiszel** [comment]
@markelliot That's true but in our case we would like to define an external object as header param (HealthCheckAuthHeader).
As you say, it needs to be primitive-like so it is forbidden currently: https://github.com/palantir/conjure/blob/676856d89e073f02490e45eb71fe21da96fc2023/conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java#L195

**Comment by markelliot** [comment]
sure, so I think the issue you're trying to file is "allow external types to be used as header parameters" (which is quite different than what's written)

**Comment by ferozco** [comment]
External types can currently be used as headers parameters, as long as their fall back type is a primitive (not including `any) or optional of primitive. To get this to work, you simply have to specify a fallback type since the default fallback is `any`.

ex:
```
types:
  imports:
    ExternalType:
      external:
        java: com.palantir.ExternalType
      base-type: string
```
