### ISSUE TITLE
Support dots in path

### ISSUE THREAD

**Issue by shzhng** [palantir/conjure#177]
## Motivation

Having a versioned path such as `/some/v1.2/path` breaks the IR compilation:

```
Segment v1.2 of path /some/v1.2/path did not match required segment patterns ^[a-zA-Z][a-zA-Z0-9_-]*$ or parameter name patterns ^\{[a-z][a-z0-9]*([A-Z0-9][a-z0-9]+)*}$ or ^\{[a-z][a-z0-9]*([A-Z0-9][a-z0-9]+)*(\Q:.+\E|\Q:.*\E)}$
```

This is a common pattern we use to maintain endpoints between microservices and between service and frontend clients.

## Proposal

If there's no specific reason that `.`s are not supported in paths, perhaps the `PathString .SEGMENT_PATTERN` could be modified to accept `.`s.

Thanks guys for open sourcing this! Really missed having this library around, i remember it being super helpful for reducing boilerplate

**Comment by iamdanfox** [comment]
:+1: sounds very reasonable relax the validation. Would you like to make a PR to the [HttpPathValidator](https://github.com/palantir/conjure/blob/master/conjure-core/src/main/java/com/palantir/conjure/defs/validator/HttpPathValidator.java#L40)?

**Comment by cbrockington** [comment]
Further to this, could we update the docs to specify what the restrictions are to the path segments?  At the moment the only definition is:

> PathString
> A PathString consists of segments separated by forward slashes, /. Segments may be literals or path parameters (see below).
> 
> When comparing multiple paths, the path with the longest concrete path should be matched first.

Would be nice to include what counts as a valid segment.
