### ISSUE TITLE
Specify case sensitivity of enum values

### ISSUE THREAD

**Issue by sfackler** [palantir/conjure#184]
conjure-java currently normalizes enum values to uppercase when deserializing, so the JSON value `"one"`, `"One"`, `"ONE"`, etc will all successfully deserialize to an `EnumExample.ONE` (and unknown variants will be upper-cased).

This behavior isn't actually specified, however.

**Comment by ferozco** [comment]
The [wire spec](https://github.com/palantir/conjure/blob/master/docs/spec/wire.md#52-container-types) states that string comparison should be used when comparing enums and the [language spec](https://github.com/palantir/conjure/blob/master/docs/spec/conjure_definitions.md#enumtypedefinition) state that all enum values must be UPPERCASE. It follows that `"ONE"` is valid but `"One"`, `"one"` are invalid. The documentation could probably be a little more explicit about the handling of such cases.

It does seem like you've found conjure-java being overly permissive. We should follow up with test cases in [conjure-validation](https://github.com/palantir/conjure-verification) and then fix things up in conjure-java

**Comment by sfackler** [comment]
Cool - should we close this and open issues on conjure-java/conjure-validation?

**Comment by ferozco** [comment]
ya if you could that would be great!
