### ISSUE TITLE
Clarify optional<binary> request and response bodies

### ISSUE THREAD

**Issue by carterkozak** [palantir/conjure#186]
### Response body:

Currently we set a 204 (no content) status for empty optionals. Do we also expect a 204 status for `binary` with zero bytes of content? What about present optional of zero bytes of data?

_Aside: Current java implementations tend to produce the expected 204 status for empty optional<binary> responses, but send `application/json` base64 encoded strings when values are present._

### Request body:

Unlike responses, requests do not have status codes.

What do we expect to differentiate an empty optional binary request and an optional binary request with zero bytes of content?

**Comment by sfackler** [comment]
This was fixed by #207, right?

**Comment by carterkozak** [comment]
Yep
