### ISSUE TITLE
Add more language keys to external types

### ISSUE THREAD

**Issue by bmoylan** [palantir/conjure#215]
In addition to `java`, can we add a `go` key to external types? I assume there are other languages that would want the same thing but don't want to suggest hypothetical use cases.

Until then, [`conjure-go`](https://github.com/palantir/conjure-go) does not support external types which are useful as an escape hatch.

cc @nmiyake

**Comment by ferozco** [comment]
Closing in favour of continuing the discussion https://github.com/palantir/conjure/issues/91
