### ISSUE TITLE
"Query parameters must be..." error message could be improved

### ISSUE THREAD

**Issue by AlexLandau** [palantir/conjure#272]
## Motivation

I'm working to get a codebase working with Conjure 4.5.1. This introduced a new error:

`java.lang.IllegalStateException: Query parameters must be enums, primitives, aliases, list, sets or optional of primitive: "mapping" is not allowed`

I didn't realize that "mapping" was an argument name here; I thought it was a description of a map-like or object-like type. I wound up grepping for `param-type: query` through a large set of source files to find candidates that may have caused the error.

## Proposal

It would generally help to identify the location of the error if the endpoint name were also included in the error message. Also, a wording like `"mapping" has an invalid type` might avoid confusion over whether it is the type or the argument name. (I assume it's too late in the process to include the location in the source file.)

**Comment by carterkozak** [comment]
This should make it easier to understand! #276
