### ISSUE TITLE
Compiled IR should be 100% deterministic

### ISSUE THREAD

**Issue by bmoylan** [palantir/conjure#316]
In godel-conjure-plugin, we're seeing ordering of type definitions in the IR change across runs. Most, but not all, of the time, it matches the order in the yaml definition. Unfortunately I don't have a reliable repo.

This is causing generated code to be unstable (given that multiple types are generated into a single `structs.conjure.go`) and fail our file checksum-based validation.

https://github.com/palantir/godel-conjure-plugin/issues/26

**Comment by iamdanfox** [comment]
When designing the IR, we actually tried to use JSON lists instead of JSON maps wherever possible to avoid this exact problem - if it's just the `types` section of the IR that can get re-ordered though, I think we could put something in that sorts these before emitting them!

**Comment by markelliot** [comment]
Conjure maps should be deterministically ordered if they're run through Conjure objects (at least for Java) because we use LinkedHashMaps instead of plain HashMaps, did we lose that guarantee along the way?

**Comment by carterkozak** [comment]
I think our conjure types with maps retain order if they're built using java builder APIs, however the `JsonSetter` annotated builder methods take `Map` which is a `HashMap` by default, so order has already been lost.

**Comment by markelliot** [comment]
Jackson's default Map type is also LinkedHashMap

**Comment by iamdanfox** [comment]
@markelliot I don't think we've lost the LinkedHashMaps thing you mentioned - I think this specific ticket is saying the YML -> IR process should always produce byte-for-byte identical IR.

**Comment by carterkozak** [comment]
I stand corrected!

**Comment by markelliot** [comment]
@iamdanfox yeah -- I guess the thing that's concerning is that things don't round-trip, and we would expect them to for the Java implementation.

**Comment by iamdanfox** [comment]
I don't think this ticket is alleging that things don't round trip - I think @bmoylan was just saying that for consistent YML, the conjure compiler should always produce the same IR.

**Comment by markelliot** [comment]
That would be true if we used LinkedHashMaps everywhere, and so my concern is that this is signal that we're not doing that.
