### ISSUE TITLE
Map key must be builtin non-any type

### ISSUE THREAD

**Issue by dansanduleac** [palantir/conjure#325]
## What happened?

In the wire spec, we imply that [map keys may only be types that have a `PLAIN` representation](https://palantir.github.io/conjure/#/docs/spec/wire?id=_52-container-types):
> A key k is serialized as a string with contents PLAIN(k).

And indeed this is what our generators expect, because we represent conjure maps as JSON objects, and JSON object keys must be strings.

We don't mention this requirement in the [Conjure definitions section](https://palantir.github.io/conjure/#/docs/spec/conjure_definitions?id=containertype), and the conjure compiler does not enforce it.

## What did you want to happen?

We should mention this constraint in the Conjure definitions section, and fail to compile code that violates it.

**Comment by dansanduleac** [comment]
Forcing all maps to comply to this might be too strong, as it's possible users might generate a map that is not meant to be serialized but only used at runtime.

Just realized this has already been mentioned in https://github.com/palantir/conjure/issues/23.

**Comment by carterkozak** [comment]
This needs to support de-aliasing and expanding external type imports to the documented base-type

**Comment by carterkozak** [comment]
This caused more confusion here: https://github.com/palantir/conjure-java/issues/605

**Comment by carterkozak** [comment]
And another break.
