### ISSUE TITLE
Conjure does not compile on Windows

### ISSUE THREAD

**Issue by vcatalano** [palantir/conjure#701]
## What happened?

When attempting to run `compileConjure` from a Windows 10 machine with IntelliJ, our team receives the following stack trace:

Failed to generate conjure IR. The command '[C:\conjure-java-example\recipe-example-api\build\conjureCompiler\bin\conjure.bat, compile, C:\conjure-java-example\recipe-example-api\build\conjure, C:\conjure-java-example\recipe-example-api\build\conjure-ir\recipe-example-api.conjure.json, --extensions, {"recommended-product-dependencies":[]}]' failed with exit code 1. Output:

> com.palantir.logsafe.exceptions.SafeIllegalArgumentException: Failed to parse extensions
> 	at com.palantir.conjure.cli.ConjureCli.parseExtensions(ConjureCli.java:116)
> 	at java.base/java.util.Optional.map(Optional.java:265)
> 	at com.palantir.conjure.cli.ConjureCli$CompileCommand.getConfiguration(ConjureCli.java:107)
> 	at com.palantir.conjure.cli.ConjureCli$CompileCommand.run(ConjureCli.java:84)
> 	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
> 	at picocli.CommandLine.access$1100(CommandLine.java:145)
> 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
> 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
> 	at picocli.CommandLine.execute(CommandLine.java:2058)
> 	at com.palantir.conjure.cli.ConjureCli.main(ConjureCli.java:46)
> Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
>  at [Source: (String)"{recommended-product-dependencies:[]}"; line: 1, column: 3]
> 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
> 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707)
> 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:632)
> 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1809)
> 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:936)
> 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:513)
> 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:377)
> 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3449)
> 	at com.palantir.conjure.cli.ConjureCli.parseExtensions(ConjureCli.java:114)
> 	... 11 more
> 

To reproduce this issue, you will need to clone the current Conjure Java example project (https://github.com/palantir/conjure-java-example) and attempt to run the `compileConjure` method with IntellJ or Windows Command Prompt.

It appears that the --extensions option is not being parsed properly by the ConjureCli.java class: `{"recommended-product-dependencies":[]}`

## What did you want to happen?

We expect the Conjure library to be compatible with Windows 10.

**Comment by mlgamble** [comment]
Thanks for you contribution to `gradle-conjure` to fix this! The latest tag (`4.12.0`) has a version bump to pull in your fix
